### ISSUE TITLE
AttributeError: 'NoneType' has no attribute 'strip'

### ISSUE THREAD

**Issue by somesmart** [chrrrisw/pyBookSearch#8]
I might be doing something stupid, but after doing a search for an ISBN, saving the results, and then trying to execute the script again, I get this error message immediately.

The full Traceback shows that it's originating from the new_book function originating in crwLibrary.py

It first fails on the self._binding = value.strip()

Any thoughts?

**Comment by chrrrisw** [comment]
It looks like the lack of exception handling or guarding on invalid values is biting us here.

self._binding = value.strip()

is assuming that the value passed in is a string, the fact that it is None suggests to me that the binding (hardcover, softcover, etc) is not being returned from the web scraping code.

You could try replacing with something along the lines of:

try:
    self._binding = value.strip()
except Exception as err:
    # Some error handling code

or just:

if value is not None:
    self._binding = value.strip()

We could also check that value is string like.

I've not got much error handling in the code, and I noticed another one the other day in the GTK interface code, so I should go through and make it more robust.

**Comment by somesmart** [comment]
I went with the if is not None option and it's working. I think the bigger problem was I had written a "None" value to the auto_library causing the issue on the second run only, but it's probably good to have the handling in there.

I'm working on some other functionality (and learning BeautifulSoup), but I'll issue a pull request after

**Comment by chrrrisw** [comment]
Glad to hear it's working. I agree - it's better to have the handling in there.
